version: '3'
services:
    db:
        image: postgres
        restart: always
        ports:
            - 5432:5432
        volumes:
            - data:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: user
            POSTGRES_PASSWORD: password
    app:
        restart: always
        build: ./
        ports:
            - 5000:5000
        working_dir: /app
        depends_on:
            - db
        volumes: 
            - ./:/app
        command: flask run --host=0.0.0.0
volumes:
    data:
